# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-18 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.TextField(max_length=254)),
                ('patientPassword', models.TextField(max_length=25)),
                ('purpose', models.TextField(max_length=500)),
                ('doctorName', models.TextField(max_length=254)),
                ('patientHward', models.TextField(max_length=25)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='StaffInfo',
        ),
    ]
