# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-18 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180318_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffinfo',
            old_name='user_id',
            new_name='uid',
        ),
    ]
